server {
    listen 80;
    listen [::]:80;
    server_name old.zonayummy.com;

    root /var/www/old_zonayummy/build;
    index index.html;

    location ^~ /.well-known/acme-challenge/ {
        default_type "text/plain";
        root /var/www/old_zonayummy/build;
    }

    location /static/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    add_header X-Content-Type-Options nosniff always;
    add_header X-Frame-Options DENY always;
}
